name = "cyclr-chat"
main = "src/index.ts"
compatibility_date = "2025-04-01"

[assets]
directory = "src/frontend"

[[d1_databases]]
binding = "DB"
database_name = "cyclr-chat-db"
database_id = "44f3c730-b24e-4e3a-85e0-db22f0b38193"
